[toolchain]

[features]
seeds = false
skip-lint = false

[programs.devnet]
stay_king = "HLtsjATCY2R9pG29kr3QWhvyuMagjZVj89qqkNyTDTVt"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/yow/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
